name: Go Stock Service CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodlari Depodan Al (Checkout)
        uses: actions/checkout@v4

      - name: Go Ortamini Kur
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Bagimliliklari Yukle (Go Mod Download)
        run: go mod download

      - name: Projeyi Derle (Build)
        run: go build -v ./...

      - name: Testleri Calistir
        run: go test -v ./...