// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/products": {
            "get": {
                "description": "Sayfa numarası, limit ve arama parametrelerine göre ürünleri listeler.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Sayfalanmış ve filtrelenmiş ürün listesini döner",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Sayfa numarası (Varsayılan: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Sayfa başına ürün sayısı (Varsayılan: 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Arama kelimesi",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ürün listesi ve sayfalama bilgisi",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Sunucu hatası",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "JSON body ile gelen ürün bilgilerini veritabanına ekler.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Sisteme yeni ürün kaydeder",
                "parameters": [
                    {
                        "description": "Ürün Bilgileri",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Oluşturulan ürün",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "400": {
                        "description": "Geçersiz istek gövdesi",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Kayıt hatası",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/products/{id}": {
            "get": {
                "description": "Ürün ID parametresi ile veritabanından ürün bilgilerini çeker.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Belirtilen ID'ye sahip ürün detayını getirir",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ürün ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ürün detayı",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Geçersiz ürün ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Ürün bulunamadı",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/products/{id}/image": {
            "post": {
                "description": "Multipart form üzerinden yüklenen görseli sunucuya kaydeder ve ProductImageUploaded olayı oluşturur.",
                "consumes": [
                    "multipart/form"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Ürüne görsel yükler ve AI Outbox olayı tetikler",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ürün ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Yüklenecek görsel dosyası",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Görsel başarıyla yüklendi",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Geçersiz ID veya eksik dosya",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Kayıt hatası",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/products/{id}/recommendations": {
            "get": {
                "description": "Redis önbelleğinden veya izole kategori benzerlik matrisinden ilgili ürün önerilerini döner.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recommendations"
                ],
                "summary": "Ürüne özel TF-IDF ve benzerlik tavsiyelerini getirir",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ürün ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tavsiye listesi",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Ürün bulunamadı",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/products/{id}/reduce-stock": {
            "post": {
                "description": "Redis Lua Script kullanarak yarış koşullarını (race conditions) engeller ve stok düşer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stock"
                ],
                "summary": "Belirtilen ürünün stok miktarını doğrudan düşürür",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Ürün ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Düşülecek miktar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ReduceStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Başarılı stok düşüşü",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Yetersiz stok veya geçersiz istek",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/stock/reserve": {
            "post": {
                "description": "Gelen order_id ile mükerrer kontrolü (idempotency) yaparak stok rezerve eder ve pazar yeri sync için outbox kaydı oluşturur.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stock"
                ],
                "summary": "Idempotent stok rezervasyonu yapar ve Outbox event tetikler",
                "parameters": [
                    {
                        "description": "Rezervasyon İstek Parametreleri",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReserveStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Başarılı rezervasyon",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Geçersiz istek, mükerrer işlem veya yetersiz stok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ReduceStockRequest": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "models.Product": {
            "type": "object",
            "properties": {
                "ai_cataloged": {
                    "type": "boolean"
                },
                "care_instructions": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "seo_title": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ReserveStockRequest": {
            "type": "object",
            "required": [
                "order_id",
                "product_id",
                "quantity"
            ],
            "properties": {
                "expiration_secs": {
                    "description": "Opsiyonel, gönderilmezse varsayılan süre kullanılır",
                    "type": "integer"
                },
                "order_id": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
