name: Go Stock Service CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # veya kullandığın Go sürümü
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run Service Unit Tests
        run: go test ./service/... -v